import json,datetime
from playwright.sync_api import sync_playwright
errs=[]
t=datetime.date.today()
with sync_playwright() as p:
    b=p.chromium.launch(); ctx=b.new_context(viewport={"width":390,"height":844},device_scale_factor=2,service_workers="block")
    for pat in ["**/www.google.com/**","**/www.gstatic.com/**","**/fonts.googleapis.com/**"]: ctx.route(pat,lambda r:r.abort())
    ctx.route("**/config.js",lambda r:r.fulfill(body="window.PLANNER_FIREBASE_CONFIG={};",content_type="text/javascript"))
    pg=ctx.new_page(); pg.on("pageerror",lambda e:errs.append(str(e)))
    pg.goto("http://localhost:8765/"); pg.wait_for_timeout(500)
    print("opens on:",pg.inner_text("#bigDate"),"| nav:",[x for x in pg.locator("#nav button span").all_inner_texts()])
    # smart quick add
    pg.click('#nav button[data-tab="plan"]'); pg.wait_for_timeout(150)
    pg.type("#qaInput","Dentist tomorrow 3pm #personal !! remind 15m",delay=5); pg.wait_for_timeout(150)
    print("hint chips:",pg.locator("#qaHint span").all_inner_texts())
    pg.screenshot(path="tests/out/n_smart.png")
    pg.press("#qaInput","Enter"); pg.wait_for_timeout(200); print("toast:",pg.inner_text(".toast span"))
    pg.click('.toast-act'); pg.wait_for_timeout(200)
    print("saved task:",pg.input_value(".sheet .inp.title"),pg.input_value('.sheet input[type="date"]'),pg.input_value('.sheet input[type="time"]'),pg.locator('.sheet .chip[aria-pressed="true"]').all_inner_texts(),pg.input_value('.sheet select[aria-label="Reminder"]'))
    pg.keyboard.press("Escape")
    for txt in ["Gym every monday 6pm for 1h #personal","Call mum at 7","Buy sun cream"]:
        pg.fill("#qaInput",txt); pg.press("#qaInput","Enter"); pg.wait_for_timeout(120)
    # focus timer from task
    pg.click('.tbody:has-text("Call mum")'); pg.click('.sheet .chip:has-text("Focus")'); pg.wait_for_timeout(300)
    pg.click('.sheet .chip:has-text("15 min")'); pg.click('.sheet button:has-text("Start focus")'); pg.wait_for_timeout(600)
    print("focus running:",pg.inner_text(".ftime"),"|",pg.inner_text(".flabel"))
    pg.screenshot(path="tests/out/n_focus.png")
    pg.click('.sheet .x[aria-label="Close"]'); pg.wait_for_timeout(300); print("pill visible:",pg.is_visible("#focusPill"),pg.inner_text("#focusPill"))
    pg.evaluate("(()=>{const s=JSON.parse(localStorage.getItem('planner.focus'));s.startedAt=Date.now()-s.duration*1000-2000;localStorage.setItem('planner.focus',JSON.stringify(s));document.dispatchEvent(new Event('visibilitychange'));})()")
    pg.wait_for_timeout(500); print("after finish pill:",pg.inner_text("#focusPill"))
    pg.click("#focusPill"); pg.wait_for_timeout(300); print("done screen:",pg.inner_text(".flabel"),"| buttons:",pg.locator(".fctrls button").all_inner_texts())
    pg.click('.fctrls button:has-text("Finish")'); pg.wait_for_timeout(300)
    print("task shows focus time:",pg.locator('.task:has-text("Call mum") .meta').inner_text())
    # templates
    pg.click('#nav button[data-tab="more"]'); pg.wait_for_timeout(200)
    print("more groups:",pg.locator(".sgroup").all_inner_texts())
    pg.screenshot(path="tests/out/n_more.png",full_page=True)
    pg.click('.mi:has-text("Templates")'); pg.click('.chip:has-text("Packing list")'); pg.wait_for_timeout(200)
    pg.click('.tplcard button:has-text("Use as a task")'); pg.wait_for_timeout(300)
    print("template -> task:",pg.input_value(".sheet .inp.title"),"steps:",pg.locator(".sheet .subrow").count()); pg.click('.sheet button:has-text("Add task")'); pg.wait_for_timeout(200)
    # countdowns
    pg.click('.back'); pg.click('.mi:has-text("Countdowns")'); pg.click('button:has-text("+ New countdown")')
    pg.fill(".sheet .inp.title","Mum's birthday"); pg.fill('.sheet input[type="date"]',(t-datetime.timedelta(days=365*50-3)).isoformat()); pg.locator('.sheet input[type="checkbox"]').first.check(); pg.locator('.sheet input[type="checkbox"]').nth(1).check()
    pg.click('.sheet .emojis button:has-text("🎂")'); pg.click('.sheet button:has-text("Add")'); pg.wait_for_timeout(200)
    pg.click('button:has-text("+ New countdown")'); pg.fill(".sheet .inp.title","Holiday in Lisbon"); pg.fill('.sheet input[type="date"]',(t+datetime.timedelta(days=40)).isoformat()); pg.click('.sheet .emojis button:has-text("✈️")'); pg.click('.sheet button:has-text("Add")'); pg.wait_for_timeout(200)
    print("countdowns:",[x.replace("\n"," | ") for x in pg.locator(".cdcard").all_inner_texts()])
    pg.screenshot(path="tests/out/n_cd.png")
    # subscriptions
    pg.click('#nav button[data-tab="money"]'); pg.wait_for_timeout(200)
    pg.click('button:has-text("Choose currency")'); pg.fill('.sheet input[type="search"]',"pound"); pg.wait_for_timeout(150); pg.click('.sheet .sres button:has-text("GBP")'); pg.wait_for_timeout(200)
    pg.click('button:has-text("+ Add a subscription or bill")'); pg.fill('.sheet .inp.title',"Netflix"); pg.fill('.sheet input[aria-label="Amount"]',"10.99")
    pg.fill('.sheet input[aria-label="Next payment"]',(t-datetime.timedelta(days=62)).isoformat()); pg.select_option('.sheet select[aria-label="Icon"]',"📺"); pg.click('.sheet .actions button:has-text("Add")'); pg.wait_for_timeout(2200)
    print("subs row:",pg.locator('.txn:has-text("Netflix")').first.inner_text().replace("\n"," | "))
    print("auto-logged Netflix expenses:",pg.locator('.cols2 .mcol:last-child .txn:has-text("Netflix")').count(),"| spent:",pg.inner_text(".bigamt"))
    pg.screenshot(path="tests/out/n_money.png",full_page=True)
    # insights
    pg.click('#nav button[data-tab="more"]'); pg.click('.mi:has-text("Insights")'); pg.wait_for_timeout(300)
    print("insight charts:",pg.locator(".chart svg").count(),"| stats:",[x.replace("\n"," ") for x in pg.locator(".stat").all_inner_texts()][:4])
    pg.screenshot(path="tests/out/n_ins.png",full_page=True)
    # home + customise
    pg.click('#nav button[data-tab="home"]'); pg.wait_for_timeout(300)
    print("home widgets:",pg.locator(".wdg .wdh b").all_inner_texts())
    pg.screenshot(path="tests/out/n_home.png",full_page=True)
    pg.click("#homeCustom"); pg.wait_for_timeout(200)
    pg.locator('.dashrow:has-text("Quick links") .seg button:has-text("Off")').click()
    pg.locator('.dashrow:has-text("Countdowns") button[aria-label="Move up"]').click(); pg.locator('.dashrow:has-text("Countdowns") button[aria-label="Move up"]').click()
    pg.locator('.dashrow:has-text("Goals") .seg button:has-text("Small")').click()
    pg.click('.sheet .actions button:has-text("Save")'); pg.wait_for_timeout(300)
    print("after customise:",pg.locator(".wdg .wdh b").all_inner_texts())
    # bottom bar
    pg.click('#nav button[data-tab="more"]'); pg.click('.mi:has-text("Settings")'); pg.wait_for_timeout(300)
    pg.click('.setrow:has-text("Bottom bar") button'); pg.click('.sheet button[aria-label="Remove Money"]'); pg.click('.sheet .chip:has-text("+ Links")'); pg.click('.sheet .actions button:has-text("Save")'); pg.wait_for_timeout(200)
    print("new nav:",pg.locator("#nav button span").all_inner_texts())
    # app lock
    pg.click('.setrow:has-text("App lock") button:has-text("Set PIN")'); pg.wait_for_timeout(200)
    ins=pg.locator(".sheet .pinin"); ins.nth(0).fill("2468"); ins.nth(1).fill("2468"); pg.click('.sheet button:has-text("Save PIN")'); pg.wait_for_timeout(1200)
    print("lock toast:",pg.inner_text(".toast span"))
    pg.reload(); pg.wait_for_timeout(700)
    print("locked on reopen:",pg.is_visible("#lockScreen"),"| content hidden:",pg.evaluate("getComputedStyle(document.querySelector('.wrap')).visibility"))
    pg.screenshot(path="tests/out/n_lock.png")
    for d in "1111": pg.click(f'.pkey:text-is("{d}")')
    pg.wait_for_timeout(1200); print("wrong pin msg:",pg.inner_text(".pmsg"))
    for d in "2468": pg.keyboard.press(d)
    pg.wait_for_timeout(1400); print("unlocked:",not pg.is_visible("#lockScreen"),"| on:",pg.inner_text("#bigDate"))
    # forgot PIN (local) -> erase
    pg.click('#nav button[data-tab="more"]'); pg.click('.mi:has-text("Settings")'); pg.wait_for_timeout(300); pg.click('.setrow:has-text("Lock now") button'); pg.wait_for_timeout(300)
    pg.click('#lockScreen .linkbtn'); pg.wait_for_timeout(200); print("forgot sheet over lock:",pg.is_visible(".scrim.overlock h3"),pg.inner_text(".scrim.overlock h3"))
    pg.keyboard.press("Escape")
    b.close()
print("ERRORS:",errs)
